# Generated by Django 6.0.6 on 2026-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_booking_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
