# Generated by Django 6.0.6 on 2026-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
